name: Deploy Project

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".eslintrc"
      - ".prettierrc"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Generate Environment Variables File
        run: |
          echo "REACT_APP_API_BASEURL=${{secrets.REACT_APP_API_BASEURL}}" >> .env
          REACT_APP_KAKAO_CLIENT_ID=${{secrets.REACT_APP_KAKAO_CLIENT_ID}} >>.env
          REACT_APP_KAKAO_REDIRECT_URI=${{secrets.REACT_APP_KAKAO_REDIRECT_URI}} >>.env
          REACT_APP_NAVER_CLIENT_ID=${{secrets.REACT_APP_NAVER_CLIENT_ID}} >>.env
          REACT_APP_NAVER_REDIRECT_URI=${{secrets.REACT_APP_NAVER_REDIRECT_URI}} >>.env
          cat .env

      - name: Install dependencies
        run: npm install

      - name: Build static file
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://it-hunters
